### ISSUE TITLE
.toml file does not get converted to string

### ISSUE THREAD

**Issue by CodeSpent** [servall/toml-loader#4]
**1. Expected Result:**
.toml file is converted to string.

**2. Actual Result:***
.toml file is still read as .toml.

**3. Steps to reproduce**

- Create VueJS application using vue-cli-3
- Add toml-loader rules to `babel.config.js`
- Import a .toml file.

***netlify.toml***
```
[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/codespent"
  status = 302
```

***babel.config.js***
```
module.exports = {
  presets: [
    ['@vue/app', {
      rules: [{
        test: /\.toml$/,
        use: {
          loader: '@servall/toml-loader'
        }
      }]
    }]
  ]
}
```

In my component I import `netlify.toml` and `console.log` the result which tells me `redirects is not defined` indicating that it is evaluating the file as a .toml file rather than a string.

**Comment by joelgallant** [comment]
@CodeSpent what do you mean by 'converted to string'?

**Comment by joelgallant** [comment]
@CodeSpent if you had a small example I can try and help here, will close soon without more info
